// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkerfBpModkq1bcbDB_9nd-7eB3RbnR7Y',
    appId: '1:268813465988:web:2343c1adafc930f3afc5d1',
    messagingSenderId: '268813465988',
    projectId: 'delux-eeed5',
    authDomain: 'delux-eeed5.firebaseapp.com',
    storageBucket: 'delux-eeed5.firebasestorage.app',
    measurementId: 'G-ZGMB0VJM3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCgSJ9odH9L8SAlPJmUEnvhkauPfqOzg8',
    appId: '1:268813465988:android:40a83544beaa625eafc5d1',
    messagingSenderId: '268813465988',
    projectId: 'delux-eeed5',
    storageBucket: 'delux-eeed5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANfZWyS1lhvH1phviN4OXZ1aYpTN5Wlwo',
    appId: '1:268813465988:ios:e47a339a3027d349afc5d1',
    messagingSenderId: '268813465988',
    projectId: 'delux-eeed5',
    storageBucket: 'delux-eeed5.firebasestorage.app',
    iosBundleId: 'com.example.delux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANfZWyS1lhvH1phviN4OXZ1aYpTN5Wlwo',
    appId: '1:268813465988:ios:e47a339a3027d349afc5d1',
    messagingSenderId: '268813465988',
    projectId: 'delux-eeed5',
    storageBucket: 'delux-eeed5.firebasestorage.app',
    iosBundleId: 'com.example.delux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkerfBpModkq1bcbDB_9nd-7eB3RbnR7Y',
    appId: '1:268813465988:web:3e46700cb9a14433afc5d1',
    messagingSenderId: '268813465988',
    projectId: 'delux-eeed5',
    authDomain: 'delux-eeed5.firebaseapp.com',
    storageBucket: 'delux-eeed5.firebasestorage.app',
    measurementId: 'G-C0Z06S1550',
  );
}
